### ISSUE TITLE
.idea folder

### ISSUE THREAD

**Issue by bwhyman** [LLL-zqvr/basic-code#1]
应该把.idea文件夹忽略。idea本地配置不应该提交。想想，如果是eclipse拉取项目怎么办

**Comment by LLL-zqvr** [comment]
已解决，感谢(´▽｀)

**Comment by LLL-zqvr** [comment]
> 应该把.idea文件夹忽略。idea本地配置不应该提交。想想，如果是eclipse拉取项目怎么办

已解决，感谢(´▽｀)

**Comment by bwhyman** [comment]
可以close此issue 👍
